name: Deploy to Staging
on:
  push:
    branches: [main]

jobs:
  redeploy_everything:
    runs-on: ubuntu-latest
    name: Deploying everything to the stage cluster
    steps:
      - run: |
          echo "${{secrets.SSH_PRIVATE_KEY}}" &> ~/ssh_key
          mkdir -p /home/runner/.ssh
          ls /home/runner/.ssh
          touch /home/runner/.ssh/knows_hosts
          echo "${{secrets.KNOWN_HOSTS}}" &> /home/runner/.ssh/knows_hosts
          chmod 700 /home/runner/ssh_key
          ssh -i ~/ssh_key ubuntu@3.135.62.54
          cd monoturbo/ && git pull
          pnpm install 
          pnpm run build
          pm2 restart fe-server
          pm2 restart ws-server
          pm2 restart http-server
